name: cb
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cycler=0.10.0
  - dbus=1.13.18
  - expat=2.4.1
  - fftw=3.3.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.10.4
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.6
  - gettext=0.19.8.1
  - ghostscript=9.54.0
  - giflib=5.2.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - gobject-introspection=1.68.0
  - graphite2=1.3.13
  - graphviz=2.42.3
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=2.4.0
  - icu=58.2
  - imagemagick=7.0.11_12
  - intel-openmp=2021.3.0
  - jbig=2.1
  - joblib=1.0.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - latexmk=4.55
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.3
  - libgomp=11.1.0
  - libiconv=1.16
  - libpng=1.6.37
  - librsvg=2.50.3
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=1.0.3
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.2
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pandas=1.3.2
  - pango=1.42.4
  - pcre=8.45
  - perl=5.20.3.1
  - pillow=8.3.1
  - pip=21.0.1
  - pixman=0.38.0
  - pkg-config=0.29.2
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.8.11
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - qt=5.9.7
  - readline=8.1
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.2
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - tornado=6.1
  - wheel=0.37.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.2
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - alabaster
    - anyio
    - argon2-cffi
    - arrow
    - attrs
    - babel
    - backcall
    - backports-entry-points-selectable
    - beautifulsoup4
    - binaryornot
    - black
    - bleach
    - cffi
    - cfgv
    - chardet
    - charset-normalizer
    - click
    - colorama
    - cookiecutter
    - debugpy
    - decorator
    - defusedxml
    - deprecated
    - distlib
    - docutils
    - entrypoints
    - filelock
    - future
    - gitdb
    - gitpython
    - greenlet
    - identify
    - idna
    - imagesize
    - importlib-metadata
    - importlib-resources
    - iniconfig
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jinja2
    - jinja2-time
    - jsonschema
    - jupyter-book
    - jupyter-cache
    - jupyter-client
    - jupyter-core
    - jupyter-server
    - jupyter-server-mathjax
    - jupyter-sphinx
    - jupyterlab-widgets
    - jupytext
    - latexcodec
    - linkify-it-py
    - markdown-it-py
    - markupsafe
    - matplotlib-inline
    - mdit-py-plugins
    - mistune
    - mypy-extensions
    - myst-nb
    - myst-parser
    - nbclient
    - nbconvert
    - nbdime
    - nbformat
    - nest-asyncio
    - nodeenv
    - notebook
    - openreview-py
    - packaging
    - pandocfilters
    - parso
    - pathspec
    - pexpect
    - pickleshare
    - platformdirs
    - pluggy
    - poyo
    - pre-commit
    - prometheus-client
    - prompt-toolkit
    - ptyprocess
    - py
    - pybtex
    - pybtex-docutils
    - pycparser
    - pycryptodome
    - pygments
    - pyjwt
    - pylatexenc
    - pyrsistent
    - pytest
    - python-slugify
    - pyyaml
    - pyzmq
    - requests
    - requests-unixsocket
    - send2trash
    - setuptools
    - smmap
    - sniffio
    - snowballstemmer
    - soupsieve
    - sphinx
    - sphinx-comments
    - sphinx-copybutton
    - sphinx-external-toc
    - sphinx-jupyterbook-latex
    - sphinx-multitoc-numbering
    - sphinx-panels
    - sphinx-thebe
    - sphinx-togglebutton
    - sphinxcontrib-applehelp
    - sphinxcontrib-bibtex
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - sphinxext-opengraph
    - sqlalchemy
    - terminado
    - testpath
    - text-unidecode
    - tld
    - toml
    - tomli
    - tox
    - tqdm
    - traitlets
    - typing-extensions
    - uc-micro-py
    - urllib3
    - virtualenv
    - wcwidth
    - webencodings
    - websocket-client
    - widgetsnbextension
    - wrapt
    - zipp
